steps:
  - id: git
    name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/StratusNetwork/docker.git
  - id: pull
    name: gcr.io/cloud-builders/docker
    args:
      - pull
      - gcr.io/$PROJECT_ID/web:master
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/web:$BRANCH_NAME
      - --cache-from=gcr.io/$PROJECT_ID/web:$BRANCH_NAME
      - --build-arg=BRANCH=$BRANCH_NAME
      - --build-arg=AUTH=$_AUTH
      - docker/web
    wait_for:
      - git
      - pull
  - id: tag
    name: gcr.io/cloud-builders/docker
    args:
      - tag
      - gcr.io/$PROJECT_ID/web:master
      - gcr.io/$PROJECT_ID/web:latest
    wait_for:
      - build
images:
  - gcr.io/$PROJECT_ID/web:$BRANCH_NAME
  - gcr.io/$PROJECT_ID/web:latest
