steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/StratusNetwork/docker.git
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/web:$BRANCH_NAME
      - --cache-from=gcr.io/$PROJECT_ID/web:$BRANCH_NAME
      - --build-arg=BRANCH=$BRANCH_NAME
      - --build-arg=AUTH=$_AUTH
      - docker/web
images:
  - gcr.io/$PROJECT_ID/web:$BRANCH_NAME
